// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrpsvqryfodfanztkwoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycHN2cXJ5Zm9kZmFuenRrd29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTE0OTcsImV4cCI6MjA3MDA2NzQ5N30.oxZFRcvx0gUWwda_h7o23HG7qf2pHnkfzU3Y30Zyerg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});